baseURL = 'https://weeks.ginatrapani.org/'
languageCode = 'en-us'
title = 'My Life in Weeks'
disableKinds = ["taxonomy", "taxonomy"]
enableEmoji = true

theme = "your-theme-name"

[params]
author = "Gina Trapani"
